apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    stack: witwickey
spec:
  type: ClusterIP
  selector:
    app: airflow
    tier: db
  ports:
    - name: postgres
      protocol: TCP
      port: 5432
      targetPort: postgres
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    stack: witwickey
spec:
  type: ClusterIP
  selector:
    app: airflow
    tier: rabbitmq
  ports:
    - name: node
      protocol: TCP
      port: 5672
      targetPort: node
    - name: management
      protocol: TCP
      port: 15672
      targetPort: management
---
apiVersion: v1
kind: Service
metadata:
  name: airflow-web
  labels:
    stack: witwickey
spec:
  type: LoadBalancer
#  loadBalancerIP: 168.61.210.66
  selector:
    app: airflow
    tier: airflow-web
  ports:
    - name: airflow-web
      protocol: TCP
      port: 80
      targetPort: airflow-web
      nodePort: 32080
---
apiVersion: v1
kind: Service
metadata:
  name: flower
  labels:
    stack: witwickey
spec:
  type: NodePort
  selector:
    app: airflow
    tier: flower
  ports:
    - name: flower
      protocol: TCP
      port: 5555
      targetPort: flower
      nodePort: 32081
---
apiVersion: v1
kind: Service
metadata:
  name: worker
  labels:
    stack: witwickey
spec:
  type: NodePort
  selector:
    app: airflow
    tier: worker
  ports:
    - name: worker
      protocol: TCP
      port: 8793
      targetPort: worker
      nodePort: 32082
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgres
  labels:
    stack: witwickey
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: airflow
        tier: db
        stack: witwickey
    spec:
      containers:
      - name: postgres
        image: postgres
        ports:
        - name: postgres
          containerPort: 5432
        env:
         - name: POSTGRES_USER
           value: "airflow"
         - name: POSTGRES_PASSWORD
           value: "airflow"
         - name: POSTGRES_DB
           value: "airflow"
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rabbitmq
  labels:
    stack: witwickey
spec:
  replicas: 1
  template:
    metadata:
      labels:
        stack: witwickey
        app: airflow
        tier: rabbitmq
    spec:
      restartPolicy: Always
      containers:
      - name: rabbitmq
        image: rabbitmq:3-management
        ports:
        - name: management
          containerPort: 15672
        - name: node
          containerPort: 5672
        env:
        - name: RABBITMQ_DEFAULT_USER
          value: airflow
        - name: RABBITMQ_DEFAULT_PASS
          value: airflow
        - name: RABBITMQ_DEFAULT_VHOST
          value: airflow
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: airflow-web
  labels:
    stack: witwickey
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: airflow
        tier: airflow-web
        stack: witwickey
    spec:
      restartPolicy: Always
      containers:
      - name: airflow-web
        image: airflow:v8.2
        env:
        - name: AIRFLOW_HOME
          value: "/usr/local/airflow"
        - name: LOAD_DAGS_EXAMPLES
          value: "false"
        - name: AIRFLOW__WEBSERVER__RBAC
          value: "true"
        ports:
        - name: airflow-web
          containerPort: 8080
        args: ["webserver"]
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 240
          periodSeconds: 120
          timeoutSeconds: 5
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: flower
  labels:
    stack: witwickey
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: airflow
        tier: flower
        stack: witwickey
    spec:
      restartPolicy: Always
      containers:
      - name: flower
        image: airflow:v8.2
        env:
        - name: AIRFLOW_HOME
          value: "/usr/local/airflow"
        - name: LOAD_DAGS_EXAMPLES
          value: "false"
        # To prevent the error: ValueError: invalid literal for int() with base 10: 'tcp://10.0.0.83:5555'
        - name: FLOWER_PORT
          value: "5555"
        - name: AIRFLOW__WEBSERVER__RBAC
          value: "true"
        ports:
        - name: flower
          containerPort: 5555
        args: ["flower"]
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: scheduler
  labels:
    stack: witwickey
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: airflow
        tier: scheduler
        stack: witwickey
    spec:
      restartPolicy: Always
      containers:
      - name: scheduler
        image: airflow:v8.2
        # volumes:
        #     - /localpath/to/dags:/usr/local/airflow/dags
        env:
        - name: AIRFLOW_HOME
          value: "/usr/local/airflow"
        - name: LOAD_DAGS_EXAMPLES
          value: "false"
        - name: AIRFLOW__WEBSERVER__RBAC
          value: "true"
        args: ["scheduler", "-n", "-1"]
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: worker
  labels:
    stack: witwickey
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: airflow
        tier: worker
        stack: witwickey
    spec:
      hostname: worker
      restartPolicy: Always
      containers:
      - name: worker
        image: airflow:v8.2
        # volumes:
        #     - /localpath/to/dags:/usr/local/airflow/dags
        env:
        - name: AIRFLOW_HOME
          value: "/usr/local/airflow"
        - name: LOAD_DAGS_EXAMPLES
          value: "false"
        - name: AIRFLOW__WEBSERVER__RBAC
          value: "true"
        ports:
        - name: worker
          containerPort: 8793
        args: ["worker"]